// Generated by CoffeeScript 1.9.3
(function() {
  var templ;

  templ = (function() {
    function templ() {
      this.models = {};
    }

    templ.prototype.bind = function(value, model) {
      var result, view_elems;
      view_elems = document.querySelectorAll('[data-model="' + model + '"]');
      result = "var p=[];p.push('" + html.replace(/[\r\n\t]/g, " ").replace(/\@\{\#(.*?)\}/g, "');p.push($1);p.push('").replace(/@\{/g, "');").replace(/\}/g, "p.push('") + "');return p.join('');";
      return n;
    };

    return templ;

  })();

}).call(this);
